# dumb pipeline
image: cta-computing/dpps/CTADIRAC

variables:
  GIT_STRATEGY: clone

build:
  script:
    - cd ..
    - mkdir CTADIRAC_test
    - mv CTADIRAC CTADIRAC_test/
    - cd CTADIRAC_test
    - mkdir -p myDirac; cd myDirac
    - wget http://cccta-dataserver.in2p3.fr/data/install_dirac_client.sh
    - chmod +x install_dirac_client.sh
    - ./install_dirac_client.sh
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - pwd
    - ls -l
    - python CTADIRAC/tests/ci_example.py
